-- CREAR ID TRABAJADOR
CREATE OR REPLACE TRIGGER MVCD_ID_TRABAJADOR
BEFORE INSERT ON MVCD_TRABAJADORES
FOR EACH ROW
DECLARE
    ID_TRABAJADOR_T NUMBER := 0;
BEGIN
    SELECT NVL(MAX(ID_TRABAJADOR)+1,1) INTO ID_TRABAJADOR_T
    FROM MVCD_TRABAJADORES;
    :NEW.ID_TRABAJADOR := ID_TRABAJADOR_T;
END;

-- CREAR TRABAJADOR
CREATE OR REPLACE PROCEDURE MVCD_C_TRABAJADOR(
    NOMBRE_TRABAJADOR_P VARCHAR2,
    APELLIDO1_TRABAJADOR_P VARCHAR2,
    APELLIDO2_TRABAJADOR_P VARCHAR2,
    TELEFONO_TRABAJADOR_P VARCHAR2,
    CORREO_P VARCHAR2,
    ID_REGION_P NUMBER,
    ID_ROL_P NUMBER
)
IS
BEGIN
    LOCK TABLE MVCD_TRABAJADORES IN ROW EXCLUSIVE MODE;
    INSERT INTO MVCD_TRABAJADORES(TELEFONO_TRABAJADOR,CORREO,NOMBRE_TRABAJADOR,APELLIDO1_TRABAJADOR,APELLIDO2_TRABAJADOR,ID_REGION,ID_ROL)
        VALUES(TELEFONO_TRABAJADOR_P,UPPER(CORREO_P),UPPER(NOMBRE_TRABAJADOR_P),UPPER(APELLIDO1_TRABAJADOR_P),UPPER(APELLIDO2_TRABAJADOR_P),ID_REGION_P,ID_ROL_P);
    COMMIT;
    EXCEPTION
        WHEN STORAGE_ERROR THEN
            RAISE_APPLICATION_ERROR(-6500, 'ERROR DE MEMORIA');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20010, 'ERROR DESCONOCIDO');
    ROLLBACK;
END;

-- (READ) LEER TRABAJADOR

-- (UPDATE) ACTUALIZAR TRABAJADOR

CREATE OR REPLACE PROCEDURE MVCD_U_TRABAJADOR(
    ID_TRABAJADOR_P NUMBER,
    ID_ROL_P NUMBER,
    TELEFONO_TRABAJADOR_P NUMBER DEFAULT NULL
)
IS
BEGIN
    LOCK TABLE MVCD_TRABAJADORES IN ROW EXCLUSIVE MODE;
    IF (TELEFONO_TRABAJADOR_P IS NULL) THEN
        UPDATE MVCD_TRABAJADORES SET
            ID_ROL = ID_ROL_P
        WHERE ID_TRABAJADOR_P = ID_TRABAJADOR;
    ELSE
        UPDATE MVCD_TRABAJADORES SET
            ID_ROL = ID_ROL_P,
            TELEFONO_TRABAJADOR = TELEFONO_TRABAJADOR_P
        WHERE ID_TRABAJADOR_P = ID_TRABAJADOR;
    END IF;
    COMMIT;
    EXCEPTION
        WHEN STORAGE_ERROR THEN
            RAISE_APPLICATION_ERROR(-6500, 'ERROR DE MEMORIA');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20010, 'ERROR DESCONOCIDO');
    ROLLBACK;
END;

-- (DELETE) BORRAR TRABAJADOR

CREATE OR REPLACE PROCEDURE MVCD_D_TRABAJADOR(
    ID_TRABAJADOR_P NUMBER
)
IS
BEGIN
    LOCK TABLE MVCD_TRABAJADORES IN ROW EXCLUSIVE MODE;
    DELETE FROM MVCD_TRABAJADORES WHERE ID_TRABAJADOR = ID_TRABAJADOR_P;
    COMMIT;
    EXCEPTION
        WHEN STORAGE_ERROR THEN
            RAISE_APPLICATION_ERROR(-6500, 'ERROR DE MEMORIA');
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20010, 'ERROR DESCONOCIDO');
    ROLLBACK;
END;
